---
title: "your_title_goes_here"
author: "your_name_goes_here"
date: last-modified
format:
  html:
    embed-resources: true
    theme:
      - default
knitr:
  opts_chunk:        ########## set global options ############
    collapse: true   # keep code from blocks together (if shown)
    echo: false      # don't show code
    message: true    # show messages
    warning: true    # show warnings
    error: true      # show error messages
    comment: ""      # don't show ## with printed output
    dpi: 100         # image resolution (typically 300 for publication)
    fig-width: 6.5   # figure width
    fig-height: 4.0  # figure height
    R.options:    
      digits: 3    # round to three digits
editor: source
---

```{r, tidyverse-tidymodels}
#| echo: false
library(conflicted)
suppressPackageStartupMessages(library(tidymodels))
tidymodels_prefer()
suppressPackageStartupMessages(library(tidyverse))

# suppress "`summarise()` has grouped output by " messages
options(dplyr.summarise.inform = FALSE)
```

```{r, other-packages}
#| echo: false
library(rio)
# library()  # type a package name inside the parentheses
```

```{r, load-data}
#| echo: false
# raw_data <- import("")  # your data file goes inside the ""

```

