---
title: "your_title_goes_here"
author: "your_name_goes_here"
date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    number_sections: false
bibliography: [references.bib, packages.bib]
csl: the-new-england-journal-of-medicine.csl
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(
                     ########## set global options ############
    echo = FALSE,    # don't show code
    collapse = TRUE, # keep code from blocks together (if shown)
    message = TRUE,  # show messages
    warning = TRUE,  # show warnings
    error = TRUE,    # show error messages
    comment = ""     # don't show ## with printed output
)

# R's default rounding is to show 7 digits. This rounds results to 3 digits.
options(digits = 3)
```

```{r tidyverse, echo=FALSE}
library(conflicted)
conflict_prefer("filter", "dplyr", quiet = TRUE)
conflict_prefer("lag", "dplyr", quiet = TRUE)
suppressPackageStartupMessages(library(tidyverse))

# suppress "`summarise()` has grouped output by " messages
options(dplyr.summarise.inform = FALSE)
```

# Introduction

# Methods
Analyses were conducted with `r stringr::word(R.Version()$version.string, 1, 3)` with the `tidyverse` (`r packageVersion("tidyverse")`), `rUM` (`r packageVersion("rUM")`), `table1` (`r packageVersion("table1")`) packages used to preprocess and summarize data.[@R-base; @R-tidyverse; @tidyverse2019; @R-rUM; @R-table1]

# Results

# Conclusion

# References {-}

```{r include=FALSE}
# automatically create a bib database for loaded R packages & rUM
knitr::write_bib(
  c(
    .packages(),
    "rUM",
    "table1"
  ),
  "packages.bib"
)
```
